src/e_psu/admin_kelola/urls.py
from django.urls import path

from . import views

app_name = "admin_kelola"
urlpatterns = [
    path("login", views.login_admin_kelola, name="login"),
    path("register", views.register_admin_kelola, name="register"),
    path("logout", views.logout_admin_kelola, name="logout"),
    path("profile", views.display_profile_view, name="display_profile"),
    path("profile/edit", views.change_profile_view, name="change_profile"),
    path("dashboard", views.index, name="index"),
    path("perwakilan_penghuni/tambah", views.perwakilan_penghuni_tambah, name="perwakilan_penghuni_tambah"),
    path("perwakilan_penghuni/hapus/<int:id>", views.perwakilan_penghuni_hapus, name="perwakilan_penghuni_hapus"),
    path("laporan/tambah", views.laporan_tambah, name="laporan_tambah"),
    path("laporan/persetujuan/<int:id>", views.detail_form_persetujuan_view, name="laporan_persetujuan"),
    path("laporan/tampil/<int:id>", views.laporan_tampil, name="laporan_tampil"),
    path("laporan/ubah/<int:id>", views.laporan_ubah, name="laporan_ubah"),
    path("laporan/hapus/<int:id>", views.laporan_hapus, name="laporan_hapus"),
    path("serah_terima/tambah", views.serah_terima_tambah, name="serah_terima_tambah"),
    path("serah_terima/tampil/<int:id>", views.serah_terima_tampil, name="serah_terima_tampil"),
    path("serah_terima/ubah/<int:id>", views.serah_terima_ubah, name="serah_terima_ubah"),
    path("serah_terima/hapus/<int:id>", views.serah_terima_hapus, name="serah_terima_hapus"),
]

src/e_psu/e_psu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import home_view


urlpatterns = [
    path("", home_view, name="home"),
    path('admin/', admin.site.urls),
    path('warga/', include("warga.urls")),
    path('admin_kelola/', include("admin_kelola.urls")),
    path('admin_skpd/', include("admin_skpd.urls")),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete"),
    # path('accounts/', include('django.contrib.auth.urls')), # for authentication view
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/e_psu/admin_kelola/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput
from django.core.validators import MinLengthValidator

from .models import AdminKelola
    
class AdminKelolaRegistrationForm(forms.ModelForm):    
    class Meta:
        model = AdminKelola
        fields = ['nama']

src/e_psu/laporan/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput

from .models import BerkasLaporan

class BerkasLaporanClearableFileInput(ClearableFileInput):
    initial_text = 'Saat ini'
    input_text = 'Ubah'

class BerkasLaporanForm(forms.ModelForm):
    class Meta:
        model = BerkasLaporan
        fields = ("nama_psu_laporan", "judul_laporan", "deskripsi_laporan", "foto_laporan",)

    nama_psu_laporan = forms.CharField(label="Nama PSU", max_length=100)
    judul_laporan = forms.CharField(label="Judul Laporan", max_length=100)
    deskripsi_laporan = forms.CharField(widget=forms.Textarea,label="Deskripsi Laporan")
    foto_laporan = forms.ImageField(widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}), required=False)

class UpdateStatusForm(forms.ModelForm):
    class Meta:
        model = BerkasLaporan
        fields = ("status_laporan",)
    
    status_laporan_choices = [
        ('BELUM', 'Belum Diproses'),
        ('SEDANG', 'Sedang Diproses'),
        ('SUDAH', 'Selesai Diproses')
    ]
    status_laporan = forms.ChoiceField(widget=forms.RadioSelect, choices=status_laporan_choices, label="Status Laporan")

class UpdatePenangananForm(forms.ModelForm):
    class Meta:
        model = BerkasLaporan
        fields = ("bentuk_penanganan_laporan",)

    bentuk_penanganan_laporan = forms.CharField(widget=forms.Textarea, label="Penanganan Terhadap Laporan")

class PersetujuanLaporan(forms.ModelForm):
    class Media:
        js = ['js/persetujuan_laporan.js']
        
    class Meta:
        model = BerkasLaporan
        fields = ('is_approve', 'alasan_ditolak')
    
    is_approve = forms.TypedChoiceField(
                    label="Pilih Persetujuan",
                    coerce=lambda x: x =='True',
                    choices=((False, 'Tolak Laporan'), (True, 'Setujui Laporan')),
                    widget=forms.RadioSelect
                )

src/e_psu/serah_terima/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput

from .models import Dokumen
from data_proyek.models import DataProyek

class DokumenClearableFileInput(ClearableFileInput):
    initial_text = 'Saat ini'
    input_text = 'Ubah'
    clear_checkbox_label = 'hapus'

class DokumenForm(forms.ModelForm):
    class Media:
        js = ['js/serah_terima.js']

    class Meta:
        model = Dokumen
        exclude = ['admin_kelola',]

    video = forms.FileField(widget=DokumenClearableFileInput(attrs={'accept': 'video/*'}))
    foto = forms.ImageField(widget=DokumenClearableFileInput(attrs={'accept': 'image/*'}))
    salinan_laporan = forms.FileField(widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    status_pengelolaan_text = forms.CharField(required=False,label="Status Pengelolaan", max_length=100)
    pola_pengelolaan_text = forms.CharField(required=False,label="Pola Pengelolaan", max_length=100)
    regulasi_pemanfaatan_psu_text = forms.CharField(required=False,label="Regulasi Pemanfaatan PSU", max_length=100)
    status_pengelolaan = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    pola_pengelolaan = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    regulasi_pemanfaatan_psu = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    data_proyek = forms.ModelChoiceField(queryset=DataProyek.objects.all(),label="Lokasi Proyek")

    def clean(self):
        super().clean()
        status_pengelolaan_text = self.cleaned_data.get('status_pengelolaan_text', None)
        status_pengelolaan = self.cleaned_data.get('status_pengelolaan', None)
        if not status_pengelolaan_text and not status_pengelolaan:
            self.add_error('status_pengelolaan', 'Status Pengelolaan diperlukan')
        
        pola_pengelolaan_text = self.cleaned_data.get('pola_pengelolaan_text', None)
        pola_pengelolaan = self.cleaned_data.get('pola_pengelolaan', None)
        if not pola_pengelolaan_text and not pola_pengelolaan:
            self.add_error('pola_pengelolaan', 'Pola Pengelolaan diperlukan')

        regulasi_pemanfaatan_psu_text = self.cleaned_data.get('regulasi_pemanfaatan_psu_text', None)
        regulasi_pemanfaatan_psu = self.cleaned_data.get('regulasi_pemanfaatan_psu', None)
        if not regulasi_pemanfaatan_psu_text and not regulasi_pemanfaatan_psu:
            self.add_error('regulasi_pemanfaatan_psu', 'Regulasi Pemanfaatan PSU diperlukan')

        return self.cleaned_data

src/e_psu/admin_kelola/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from .forms import AdminKelolaRegistrationForm
from perwakilan_penghuni.forms import PerwakilanPenghuniForm
from account.forms import RegisterForm, LoginForm, EditAccountForm
from django.db import transaction
from perwakilan_penghuni.models import PerwakilanPenghuni
from serah_terima.models import Dokumen
from laporan.models import BerkasLaporan
from serah_terima.forms import DokumenForm
from laporan.forms import BerkasLaporanForm, PersetujuanLaporan
from account.decorators import admin_kelola_required, anonymous_required, superuser_admin_kelola_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from e_psu.helpers import paginate_object
from .models import AdminKelola
# Create your views here.
dokumen_list = Dokumen.objects.select_related()
laporan_reject_list = BerkasLaporan.objects.filter(is_approve=False)
laporan_accepted_list = BerkasLaporan.objects.filter(is_approve=True)
perwakilan_penghuni_list = PerwakilanPenghuni.objects.all()  
laporan_null_approve_list = BerkasLaporan.objects.filter(is_approve=None)

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def index(request):
    page = request.GET.get('page', 1)

    page_dokumens = paginate_object(dokumen_list, 10, page)

    page_laporans_reject = paginate_object(laporan_reject_list, 10, page)

    page_laporans_accepted = paginate_object(laporan_accepted_list, 10, page)

    page_perwakilan_penghunis = paginate_object(perwakilan_penghuni_list, 10, page)

    page_laporans_null_approve = paginate_object(laporan_null_approve_list, 10, page)
    
    return render(request, "admin_kelola/index.html", {
        'dokumens' : page_dokumens,
        'laporans_reject': page_laporans_reject,
        'laporans_accepted': page_laporans_accepted,
        'perwakilan_penghunis': page_perwakilan_penghunis,
        'laporans_null_approve': page_laporans_null_approve
    })

@superuser_admin_kelola_required
@transaction.atomic
def register_admin_kelola(request):
    account = RegisterForm(request.POST or None, prefix='account')
    admin_kelola = AdminKelolaRegistrationForm(request.POST or None, prefix='admin_kelola')
    context = {
        "admin_kelola_form" : admin_kelola,
        "account_form" : account
    }
    if account.is_valid() and admin_kelola.is_valid():
        user = account.save(commit=False)
        user.user_type = 1
        user.save()
        admin_kelola_data = admin_kelola.save(commit=False)
        admin_kelola_data.user = user
        admin_kelola_data.save()
        return redirect('admin_kelola:index')
    return render(request, 'admin_kelola/auth/register.html', context)

@anonymous_required
def login_admin_kelola(request):
    account = LoginForm(data=request.POST or None, request=request, prefix='admin')
    context = {
        "form" : account
    }
    if account.is_valid():
        return redirect('admin_kelola:index')
    return render(request, 'admin_kelola/auth/login.html', context)

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def logout_admin_kelola(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def perwakilan_penghuni_tambah(request):    
    perwakilan_penghuni = PerwakilanPenghuniForm(request.POST or None, prefix='perwakilan_penghuni')
    context = {
        "perwakilan_penghuni_form" : perwakilan_penghuni
    }

    if request.method == 'POST':
        form = PerwakilanPenghuniForm(request.POST)
        if perwakilan_penghuni.is_valid():
            if not PerwakilanPenghuni.objects.filter(warga=request.POST['perwakilan_penghuni-warga'], data_proyek=request.POST['perwakilan_penghuni-data_proyek']):
                perwakilan_penghuni.save()
            messages.success(request, f'Perwakilan penghuni berhasil ditambahkan.', extra_tags='perwakilan_penghuni')
            return redirect('admin_kelola:index')

    return render(request, 'admin_kelola/perwakilan_penghuni/tambah.html', context)

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def perwakilan_penghuni_hapus(request, id):
    try:
        perwakilan_penghuni = PerwakilanPenghuni.objects.get(id=id)
    except PerwakilanPenghuni.DoesNotExist:
        return redirect('admin_kelola:index')

    perwakilan_penghuni.delete()
    messages.success(request, f'Dokumen berhasil dihapus.', extra_tags='perwakilan_penghuni')
    return redirect('admin_kelola:index')

# SERAH TERIMA
@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_tambah(request):    
    if request.method == 'POST':
        form = DokumenForm(request.POST, request.FILES)
        if form.is_valid():
            admin = AdminKelola.objects.get(pk=request.user.id)
            form_serah_terima = form.save(commit=False)
            form_serah_terima.admin_kelola = admin
            form_serah_terima.save()
            nama_psu = form.cleaned_data.get('nama_psu')
            messages.success(request, f'Dokumen berhasil ditambahkan.', extra_tags='serah_terima')
            return redirect('admin_kelola:index')
    else:
        form = DokumenForm()
    return render(request, "admin_kelola/serah_terima/tambah.html", {
        'form' : form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_tampil(request, id):
    try:
        dokumen = Dokumen.objects.get(id=id)
    except dokumen.DoesNotExist:
        return redirect('admin_kelola:index')    
    return render(request, "admin_kelola/serah_terima/tampil.html", {
        'dokumen' : dokumen
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_ubah(request, id):
    try:
        dokumen = Dokumen.objects.get(id = id)
    except Dokumen.DoesNotExist:
        return redirect('admin_kelola:index')
    
    form = DokumenForm(request.POST or None, request.FILES or None, instance = dokumen)

    if form.is_valid():
        admin = AdminKelola.objects.get(pk=request.user.id)
        form_serah_terima = form.save(commit=False)
        form_serah_terima.admin_kelola = admin
        form_serah_terima.save()
        messages.success(request, f'Dokumen berhasil diperbarui.', extra_tags='serah_terima')
        return redirect('admin_kelola:index')

    return render(request, "admin_kelola/serah_terima/ubah.html", {
        'form' : form, 'dokumen' : dokumen
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_hapus(request, id):
    try:
        dokumen = Dokumen.objects.get(id=id)
    except Dokumen.DoesNotExist:
        return redirect('admin_kelola:index')

    dokumen.delete()
    messages.success(request, f'Dokumen berhasil dihapus.', extra_tags='serah_terima')
    return redirect('admin_kelola:index')

# LAPORAN
@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_tambah(request):
    if request.method == 'POST':
        form = BerkasLaporanForm(request.POST, request.FILES)
        if form.is_valid():
            form_laporan = form.save(commit=False)
            form_laporan.status_laporan = 'BELUM'
            form_laporan.is_approve = True
            form_laporan.user_created = request.user
            form_laporan.save()
            nama_psu_laporan = form.cleaned_data.get('nama_psu_laporan')
            messages.success(request, f'Laporan {nama_psu_laporan} berhasil ditambahkan.', extra_tags='laporan')
            return redirect('admin_kelola:index')
    else:
        form = BerkasLaporanForm()

    return render(request, "admin_kelola/laporan/tambah.html", {
        'form': form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_tampil(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    return render(request, "admin_kelola/laporan/tampil.html", {
        'laporan': laporan
    })
    

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_ubah(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    
    form = BerkasLaporanForm(request.POST or None, request.FILES or None, instance = laporan)

    if form.is_valid():
        form.save()
        nama_psu = form.cleaned_data.get('nama_psu_laporan')
        messages.success(request, f'Laporan {nama_psu} berhasil diperbarui.', extra_tags='laporan')
        return redirect('admin_kelola:index')

    return render(request, 'admin_kelola/laporan/ubah.html', {
        'form': form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_hapus(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    laporan.delete()
    messages.success(request, f'Laporan {laporan.nama_psu_laporan} berhasil dihapus.', extra_tags='laporan')
    return redirect('admin_kelola:index')

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def detail_form_persetujuan_view(request, id):
    query_laporan = laporan_null_approve_list.filter(id=id)
    if query_laporan.count() < 1:
        return redirect('admin_kelola:index')
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    persetujuan_laporan_form = PersetujuanLaporan(request.POST or None, instance=laporan)
    if persetujuan_laporan_form.is_valid():
        persetujuan_laporan_form.save()
        nama_psu = laporan.nama_psu_laporan
        messages.success(request, f'Laporan {nama_psu} berhasil diperbarui.', extra_tags='laporan')

src/e_psu/admin_kelola/templates/admin_kelola/laporan/detail_persetujuan.html
{% extends 'header.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Berkas Laporan {{ laporan.nama_psu }}</h2>
            </div>
            <div class="card-body">
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
                <h4>Nama PSU</h4>
                <div>
                    <p>{{ laporan.nama_psu_laporan }}</p>
                </div>
                <hr class="my-4">

                <h4>Judul Laporan</h4>
                <div>
                    <p>{{ laporan.judul_laporan }}</p>
                </div>
                <hr class="my-4">

                <h4>Deskripsi Laporan</h4>
                <div style="border: 1px solid #ddd;padding: 10px 19px;margin-bottom:15px">
                    <p style="font-size:17px;">{{ laporan.deskripsi_laporan }}</p>
                </div>
                <hr class="my-4">

                <h4>Status Persetujuan</h4>
                {% if laporan.is_approve is None %}
                    <div style="background-color: #87847a;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Belum Disetujui</p>
                    </div>
                {% endif %}
                {% if laporan.is_approve == 1 %}
                    <div style="background-color: #5de038;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Sudah Disetujui</p>
                    </div>                    
                {% endif %}
                {% if laporan.is_approve == 0 %}
                    <div style="background-color: #f0765b;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Gagal Disetujui</p>
                    </div>
                    <hr class="my-4">

                    <h4>Alasan Ditolak</h4>
                    <div style="border: 1px solid #ddd;padding: 10px 19px;margin-bottom:15px">
                        <p style="font-size:17px;">{{ laporan.alasan_ditolak }}</p>
                    </div>
                {% endif %}
                <hr class="my-4">

                <h4>Status Laporan</h4>
                {% if laporan.status_laporan == 'BELUM' %}
                    <div style="background-color: #f34d30;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Belum Diproses</p>
                    </div>
                {% endif %}
                {% if laporan.status_laporan == 'SEDANG' %}
                    <div style="background-color: #fbff24;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Sedang Diproses</p>
                    </div>
                {% endif %}
                {% if laporan.status_laporan == 'SUDAH' %}
                    <div style="background-color: #03a678;width: max-content;padding: 0px 13px;">
                        <p style="color:white">Telah Diproses</p>
                    </div>
                {% endif %}
                <hr class="my-4">

                <h4>Bentuk Penanganan Terhadap Laporan</h4>
                <div>
                    {% if laporan.bentuk_penanganan_laporan is None %}
                        <p style="color:#ccc;font-style:italic">Belum ada Penanganan</p>
                    {% else %}
                    <div style="border: 1px solid #ddd;padding: 10px 19px;margin-bottom:15px">
                        <p style="font-size:17px;">{{ laporan.bentuk_penanganan_laporan }}</p>
                    </div>
                    {% endif %}
                </div>
                <hr class="my-4">

                <h4>Foto</h4>
                <div>
                    {% if laporan.foto_laporan %}
                        <img style="max-width: 100%" src="{{ laporan.foto_laporan.url }}" alt="Foto laporan {{ laporan.nama_psu_laporan }}">
                    {% else %}
                        <p style="color:#ccc;font-style:italic">Tidak ada foto</p>
                    {% endif %}
                </div>                
                <hr class="my-4">
                
                <div class="card">
                    <div class="card-header text-center">
                        <h2>Form Persetujuan</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}                    
                            {{ persetujuan_laporan_form | crispy }}
                            <a href="{% url 'admin_kelola:index' %}" type="button" class="btn btn-danger">
                                Batal
                            </a>
                            <button type="submit" class="btn btn-success"> Update Persetujuan </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{persetujuan_laporan_form.media}}
{% endblock %}

src/e_psu/admin_kelola/templates/admin_kelola/laporan/index.html
{% extends "header.html" %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Laporan Masyarakat</h2>
            </div>
            <div class="card-body">
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
                <a href="{% url 'admin_kelola:laporan_tambah' %}" class="btn btn-success">Tambah</a>
                <table class="mt-2 table">
                    <thead class="thead-light">
                        <tr>
                            <th shape="col">Tanggal Entri</th>
                            <th shape="col">ID</th>
                            <th shape="col">Nama PSU</th>
                            <!-- <th shape="col">Perumahan</th> -->
                            <th shape="col">Judul Laporan</th>
                            <th shape="col">Bukti Foto</th>
                            <!-- <th shape="col">Bukti Video</th> -->
                            <th shape="col">Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for laporan in laporans %}
                            <tr>
                                <td>{{ laporan.tanggal_entri_laporan }}</td>
                                <td>{{ laporan.id }}</td>
                                <td>{{ laporan.nama_psu_laporan }}</td>
                                <td>{{ laporan.judul_laporan }}</td>
                                <td>
                                    <a href="{{ laporan.foto_laporan.url }}" class="btn btn-secondary" target="_blank">Unduh Bukti Foto</a>
                                </td>
                                <!-- <td>
                                    <a href="{{ laporan.video.url }}" class="btn btn-secondary" target="_blank">Unduh Bukti Video</a>                                    
                                </td> -->
                                <td>
                                    <a href="{% url 'admin_kelola:laporan_tampil' id=laporan.id %}" type="button" class="btn btn-primary">Lihat</a>
                                    <a href="{% url 'admin_kelola:laporan_ubah' id=laporan.id %}" type="button" class="btn btn-warning">Ubah</a>
                                    <a href="{% url 'admin_kelola:laporan_hapus' id=laporan.id %}" type="button" class="btn btn-danger" 
                                        onclick="return confirm('Apakah Anda yakin untuk menghapus laporan {{ laporan.judul_laporan }}?')">
                                        Hapus
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% if laporans.has_other_pages %}
                <ul class="pagination">
                    {% if laporans.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ laporans.previous_page_number }}" class="page-link"> &laquo;</a>
                    </li>

                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link"> &laquo; </span>
                    </li>
                    {% endif %}

                    {% for i in laporans.paginator.page_range %}
                        {% if laporans.number == i %}
                            <li class="page-item active">
                                <span class="page-link">
                                    {{ i }}
                                    <span class="sr-only">(current)</span>
                                </span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="?page={{ i }}" class="page-link"> {{ i }} </a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if laporans.has_next %}
                        <li class="page-item">
                            <a href="?page={{ laporans.next_page_number }}" class="page-link"> &raquo; </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link"> &raquo; </span>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

src/e_psu/admin_kelola/templates/admin_kelola/laporan/tambah.html
{% extends "header.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container py-5">
        <div class="card-header text-center">
            <h2>Penambahan Laporan Warga</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <a href="{% url 'admin_kelola:index' %}" type="button" class="btn btn-danger">
                    Batal
                </a>
                <button type="submit" class="btn btn-success"> Tambahkan </button>
            </form>
        </div>
    </div>
{% endblock %}

src/e_psu/admin_kelola/templates/admin_kelola/laporan/ubah.html
{% extends 'header.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Ubah Laporan {{ form.nama_psu.value }}</h2>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.nama_psu_laporan | as_crispy_field }}
                    {{ form.judul_laporan | as_crispy_field }}
                    {{ form.deskripsi_laporan | as_crispy_field }}
                    
                    <div id="div_id_foto" class="form-group mb-4">
                        <label for="id_foto" class=" requiredField">
                            Foto<span class="asteriskField">*</span> 
                        </label> 
                        <div>
                            Saat ini: <br>
                            {% if laporan.foto_laporan %}
                                <div class="text-center">
                                    <img style="max-width: 100%" src="{{ form.foto_laporan.value.url }}" alt="Foto {{ form.nama_psu_laporan.value }}">
                                </div>
                            {% else %}
                                <p style="color:#ccc;font-style:italic">Tidak ada foto</p>
                            {% endif %}                            
                            Ubah: <br>
                            <input type="file" name="foto" accept="image/*" class="berkaslaporanclearablefileinput form-control-file" id="id_foto"> 
                        </div>
                    </div>
                    <hr class="my-3">
                    <a href="{{ request.META.HTTP.REFERER }}" type="button" class="btn btn-danger">Batal</a>
                    <button class="btn btn-success" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}